# Generated by Django 3.0.5 on 2020-05-02 02:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_blogtagindex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTagIndex',
            new_name='BlogTagIndexPage',
        ),
    ]
